language: node_js
node_js:
  - "10.7"
sudo: false

services:
  - xvfb
# Add your branch here to have it tested and deployed
branches:
  only:
  - master

before_install:
# Configure Git
- git config --global user.email "travis-ci@legalthings.net"
- git config --global user.name "Travis CI"

# Get all tags of git repo
- git fetch origin 'refs/tags/*:refs/tags/*'

after_success:
# Bump version
- npm install mversion -g
- test "$TRAVIS_BRANCH" != 'master' -o "$TRAVIS_PULL_REQUEST" != "false" || test -n "$(git tag --contains)" || bin/bump-version

before_deploy:
# Set environment variables for Elastic Beanstalk deploy
- export ELASTIC_BEANSTALK_ENV="pdfworker-${TRAVIS_BRANCH}"
- export ELASTIC_BEANSTALK_LABEL=$(git tag --contains)
- test -n "$ELASTIC_BEANSTALK_LABEL" || export ELASTIC_BEANSTALK_LABEL="pdfworker-${TRAVIS_COMMIT:0:7}"

deploy:
# Staging
- provider: elasticbeanstalk
  access_key_id: AKIAIWFAXQWNDAHESRAA
  secret_access_key:
    secure: "OfFCP13hnm8beIkd5IvctNvGc1tg+50knjvvbO7vhTydfOu0y1W8n+JrwBaohtWHo/DYILNBj6/1hELjbAI6HGot/wvNEfPisR3ygB/MeC02MKde4/xmxKvoHzcfe8jZnk6Ejzm6BGNhWY0XbThsCiR8JzBqrq83f7J8JUakU6dAAeppWcpXXJWqJoZ6LJBIOOQwsNhC4R8hdQttGWO/nypTb4D7mRDiwdEhWHyDQxo/PnWi1Wo7NT5Oy2pj+0V51taOFD/q7nXnLC8pnmI1RvFvROXngfXQiifSlqHOU7NeFGK2iWdLVcLD/MbbsrXfQBlx/YPZ7aiQjql/wymSNx+naLfIElzmH8jrXhovt8a6zDprl5dE2WzbldoVNDlOYFyFTVS97SPVMk9pudDj1MpsuF8UOMr11amb+/JkfCPp9mbUFbn54jiZqZVBPIzgHKEQO7JRqyghz7yHUKQwKsp4MhXuEy8nxYMwCQz9UUBcb+Jlk9dze2RWvXaU1XNnZPOyEWY7043kfKZ4CJtmw6AVOCInvv2LaqUXdrCRDYH+8qeVFCd9QBC5xMxz340UdxFqxcu7Bqt1uVOcOaq/rlDm9KQmU8e67DsBYpxh4sv0h4q+PxDW/5m2voHgD6horDM+hexJnw+jMr4xYbpmzwhxQv0nvCnqCf5KWzhPmUY="
  region: eu-west-1
  app: pdfworker
  bucket_name: elasticbeanstalk-eu-west-1-930677074220
  bucket_path: pdfworker
  on:
    all_branches: true
    condition: '"${TRAVIS_BRANCH:0:7}" != "travis-"'

# Production
- provider: elasticbeanstalk
  access_key_id: AKIAJQQQ7NJVV6B67VCA
  secret_access_key:
    secure: "iunPXTRLBD7n8kODqhx2BrGth5XZibjuw+JVub9k4giKc696CIG/yBlAM6pWBu20Ww0AqguLQfG3nFBr9FjBxRtYVASJ4hkheAswhpeUARN1R8hdDUB9sAlNojC3A1VRJNwOO9OBQMeWeUvRXtfMf1oZJ/0atF2HVQ3LC6n0wdJCFYi4V7Q6tU5gg5f6tTmu1LlUXCcOOvM6ZZ4DDOITsthMXjseS1ByPLJIIf5JCm5l5rR0xaM8LEBVvfh/kVzkB9ZF50AQJVnx5m9FuJBl3IP57N84B9DbWBCWPtmCu4Ehuk450RXJNGB2dMSNNGvqHMGrCZ7RBGgANq14BoZa8U6dJpU8Iy3lYhbJvCAz/Jw7KH5/C984oe8tWTOrjnBGc87EFSVtD7V3GQFRTSItqZD3V+SFPuXnzwhMa9RuvdaSurE6O0Mfb0Be7pETd5el7WrbsBmZzgxIT8Ojswg9f4opZWWhO7iu30tG+h2e3pwAbPoifO6NnSOODIBnFcUyxnA5d9qzQjUB+/R1VJ0OFg4USUEtMHPr8vUOQCsPZaKpbV9WCzLEWrgnlV73+nlaf7LywnwCoOGY8CS91TNZ1l3ciUOh0NgHCQ5zmXBC+okuY5DkjA8Zvpuckco1pEa2o6cRwqjrqaHOQEPfpslL3sC2n+vTKKJ+9KAfK345Rxo="
  region: eu-west-1
  app: pdfworker
  bucket_name: elasticbeanstalk-eu-west-1-044051773080
  bucket_path: pdfworker
  only_create_app_version: true
  on:
    branch: master
